title: Do Nonprofit Missions Vary by the Political Ideology of Supporting Communities? Some Preliminary Results
logo: /assets/img/rep-dem.jpg
description: Replication Files
show_downloads: false
theme: jekyll-theme-minimal
